### ISSUE TITLE
Wrong date in letsencrypt_poralix.sh

### ISSUE THREAD

**Issue by wojsmol** [poralix/directadmin-utils#3]
HI
https://github.com/poralix/directadmin-utils/blob/2a54e0bd459a9dc2d799b9477ac2482677f5321f/letsencrypt/letsencrypt_poralix.sh#L43 contents wrong date. Becouce of that https://github.com/poralix/directadmin-utils/blob/2a54e0bd459a9dc2d799b9477ac2482677f5321f/letsencrypt/letsencrypt_poralix.sh#L299-L302 is not executed.

**Comment by poralix** [comment]
Hello,

Thank you for your report. The letsencrypt.sh script (which letsencrypt_poralix.sh is based on) is originally maintained by Directadmin developers, and we only patch it to allow easy usage for big number of domains. The original script might quit if an error occurs, but our version of it will ask you what to do and try one more and more time to get a domain verification from Let's Encrypt.

So I'd suggest that you bring this issue to Directadmin developers' attention. Or provide more details on your issue here please:

- What error do you get? Full text.
- What value for LICENSE_KEY_MIN_DATE you would like to have?

Regards,
Alex.

**Comment by wojsmol** [comment]
Hi Alex
I personally don't expedience any errors but looking at this two post by John [1](https://forum.directadmin.com/showthread.php?t=53567&p=274681#post274681) and [2](https://forum.directadmin.com/showthread.php?t=53567&p=274687#post274687) the value for `LICENSE_KEY_MIN_DATE` should be changed to date of last change of LE agreements - November 15 2017 or determined automaticity.

**Comment by poralix** [comment]
OK, I see what you mean. I will check what can be done here.
